---
- name: My First Automation Play
  hosts: cisco_routers
  gather_facts: false

  tasks: 
    - name: Run show version command
      cisco.ios.ios_command:
        commands: "{{ item }}"
      loop:
        - show version
        - show ip interface brief
        - show ip route
      register: output

    - name: Print the output
      debug:
        msg: "Command output: {{ item.stdout }}"
      loop: "{{ output.results }}"
