---
- name: deploy vlans and mots to 2930 via Jinja2
  hosts: TechSW1
  gather_facts: false

  tasks:
    - name: Push Pre-Rendered Jinja Template Safely
      arubanetworks.aos_switch.arubaoss_config:
        lines: "{{ lookup('template', 'templates/Aruba2930.j2').splitlines() }}"
        match: none