---
banner: |
        #####################################################
                        welcome to Delko
        #####################################################
char: "*"        
vlans:
  - ID: 101
    name: Management
  - ID: 102
    name: Engineering

    