# commands for the loop

new_interfaces: 
  - id: 55
    ip: 172.16.55.10
    mask: 255.255.255.0
    desc: Created by Ansible (Original)

  - id: 100
    ip: 10.10.100.1
    mask: 255.255.255.0
    desc: the second int

  - id: 101
    ip: 10.10.101.1
    mask: 255.255.255.0
    desc: The Third Interface
